# Generated by Django 5.0 on 2024-01-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_delete_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='table',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.CharField(choices=[('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00'), ('22:00', '22:00'), ('23:00', '23:00')], default='18:00', max_length=5),
        ),
    ]
